AWSTemplateFormatVersion: 2010-09-09
Description: |
  이것은 CloudFormation 테스트용임  
Parameters:
  ykVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: myVPC

  ykSubnet: 
    Type: "AWS::EC2::Subnet"
    Properties: 
      VpcId: 
        !Ref ykVPC
      CidrBlock: 10.10.0.0/24
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""

Metadata:
  AWS::CloudFormation::Interface:
  ParameterGroups:
    - Label:
        default: "Network Configuration"
      Parameters:
        - ykYVP
        - ykSubnet

Mappings:
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-6869aa05
    us-west-2:
      HVM64: ami-7172b611
    us-west-1:
      HVM64: ami-31490d51
    eu-west-1:
      HVM64: ami-f9dd458a
    eu-central-1:
      HVM64: ami-ea26ce85
    ap-northeast-1:
      HVM64: ami-374db956
    ap-northeast-2:
      HVM64: ami-2b408b45
    ap-southeast-1:
      HVM64: ami-a59b49c6
    ap-southeast-2:
      HVM64: ami-dc361ebf
    ap-south-1:
      HVM64: ami-ffbdd790
    us-east-2:
      HVM64: ami-f6035893
    sa-east-1:
      HVM64: ami-6dd04501
    cn-north-1:
      HVM64: ami-8e6aa0e3
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    production:
      instanceType: t2.small  

Conditions:
  
Resources:
  #myEC2Instance:
  #  Type: AWS::EC2::Instance
  #  Properties:
  #    InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]
  #    ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', HVM64]

  ykSG:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        # we have a lot of rules because it's a perfect security group
        # finance team network
      - CidrIp: 10.11.48.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
        # marketing team network
      - CidrIp: 10.11.112.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
        # application team support network
      - CidrIp: 10.11.176.0/24
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

Transform:
  
Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref ykVPC